---

- hosts: all
  become: true
  tasks:

  - name : update repository index Ubuntu & Debian
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install apache2 and php package
    apt:
      name: 
        -apache2
        -lipapache2-mod-php
      state: latest
    when: ansible_distribution in ["debian","Ubuntu"]
  
  - name update repositorty index for centos
    dnf:
      update_cache: yes
    when ansible_distribution === "Centos"
  

  - name: install httpd & php for Centos
    dnf:
      name:
        -httpd
        -php
      state: latest
    when: ansible_distribution == "Centos" 

