---

- hosts: all
  become: true
  pre_tasks:


  - name: install updates (CentOS) 
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install update (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distributin == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php for Ubuntu servers
    tags: apache,apache2,ubuntu 
    apt:
      name: 
        -apache2
        -lipapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install httpd & php for Centos servers
    tags: apache,centos,httpd
    dnf:
      name:
        -httpd
        -php
      state: latest
    when: ansible_distribution == "Centos" 

  - name: copy dafault html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dst: /var/www/html/index.html
      owner: root
      group: root
      mode: o644

    

- hosts: db_servers
  become: true
  tasks:
 
  - name: install mariadb package (CentOS)
    tags: db,mariadb,ubuntu
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"  


  - name: install mariadb package (Ubuntu)
    tags: centos,db,mariadb
    dnf:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: insall samba package 
    tags: samba
    package:
      name: samba
      state: latest
